### ISSUE TITLE
Front Camera usage

### ISSUE THREAD

**Issue by aris-konstantinidis** [mohyghb/smart_camera_state#1]
First of all, thank you very much for this handy package!

In my case, I only need the front camera. Will the library still work as expected if I just change the camera index from `0` to `1`? 

https://github.com/mohyghb/smart_camera_state/blob/9a9de2730c3d6d529a9017d237dd62772f0aacef/lib/stream_camera_state.dart#L20

**Comment by mohyghb** [comment]
Hey Aris,

Thanks for the kind words. Yes the library will work as expected if you
change the index from 0 to 1. You could do something like this:

@override
CameraDescription get rearCamera => cameras[1];

**Comment by aris-konstantinidis** [comment]
Thank you, awesome!
