### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by aris-konstantinidis** [mohyghb/smart_camera_state#2]
How would one change the aspect ratio? Most ML pipelines need a square input (for example 256x256). How would you configure this? I need to get the biggest possible angle that the device can offer.

Thank you very much for your work, any input would be appreciated :)

**Comment by mohyghb** [comment]
Although you can update the previewSize of a camera controller, the camera image that is passed in to our event listeners will still be in the original size. I found this that might be useful [https://stackoverflow.com/questions/51348166/how-to-square-crop-a-flutter-camera-preview](url)

You can update the preview size of the controller using the code below

```
@override
  void onCameraControllerInitialized() {
    cameraController.value = cameraController.value.copyWith(previewSize: const Size(256,256));
  }
```

and you can use the code from the link above to crop the image to your desired dimensions.

**Comment by aris-konstantinidis** [comment]
Okay thank you! I will look into it :)
